import "./globals.css";
import localFont from "next/font/local";

const sf_pro = localFont({ src: "./sf-pro.woff2" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={sf_pro.className}>{children}</body>
    </html>
  );
}
